
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://jckynopecuexfamepmoh.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impja3lub3BlY3VleGZhbWVwbW9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MzQ1ODAsImV4cCI6MjA2MTAxMDU4MH0.kcS5mx6kSrYqJmU3JIDizIXXsBItQVgxqD2mOa13oqE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Configuración mejorada para evitar problemas con la sesión y autenticación
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      storage: localStorage,
      flowType: 'pkce' // Tipo de flujo más seguro para OAuth
    },
    global: {
      headers: {
        'Content-Type': 'application/json'
      }
    },
    // Añadir retries para mejorar la fiabilidad de las conexiones
    realtime: {
      params: {
        eventsPerSecond: 10
      }
    }
  }
);
